<template>
  <frontmaster>
    <div class="container">
      <!-- section heading start -->
      <div class="heading mt-5">
        <h3>SASTOWHOLESALE.COM MARKETPLACE VENDOR AGREEMENT</h3>
        <h4>
          Please read the terms &amp; conditions carefully before registering in
          sastowholesale.com
        </h4>
        <p class="note">
          ( This electronic record is generated by computer system &amp; does
          not require any physical or digital signatures. )
        </p>
      </div>
      <div class="row mt-5 mb-5">
        <div class="description">
          <ul class="list">
            <li>
              <h5>1.Introduction</h5>
              <p>
                Sastowholesale.com is a B2B &amp; B2C ecommerce launched by be
                the best Pvt. Ltd., where user can connect with the different
                supplier according to their requirements &amp; have a superior
                shopping experience.
              </p>
            </li>
            <li>
              <h5>2.General Terms</h5>
              <p>
                This sastowholesale.com marketplace vendor agreement
                (“AGREEMENT”) is an agreement between vendor and
                sastowholesale.com (Be the best Pvt. Ltd.,) Governing the use of
                sastowholesale.com marketplace as a vendor for listing and
                selling products/service through sastowholesale.com.
              </p>
            </li>
            <li>
              <h5>3.Definitions</h5>
              <ul>
                <li>
                  <strong>“Content”:</strong> means the textual, visual or audio
                  content that is encountered as part of your experience on Our
                  Website. It may include, among other things: text, images,
                  sounds, videos and animations. It includes content such as
                  advertising material, and all other product or service related
                  material Posted by you.
                </li>
                <li>
                  <strong>“Our website”:</strong> means sastowholesale.com.
                </li>
                <li>
                  <strong>“Product”:</strong> means any item offered for sale by
                  you on our website, whether physical goods or digital.
                </li>
                <li>
                  <strong>“You or Your”:</strong> means the vendor registering
                  in sastowholesale.com
                </li>
              </ul>
            </li>
            <li>
              <h5>4.Our contract</h5>
              <ul>
                <li>
                  In consideration of a sales fee charged by us, we are
                  providing an ecommerce marketplace as an arm's length
                  contractor.
                </li>
                <li>We are not partners or joint ventures.</li>
                <li>We are supporting each other for our mutual benefits.</li>
                <li>
                  When you place a Product on Our Website, you will be bound to
                  provide all the information required by the Competition and
                  Consumer Act 2010.
                </li>
                <li>
                  Although we are not a party to your contract with a buyer
                  introduced to you VIA our website, we may remove your products
                  &amp; charge you if a customer or our website visitor has a
                  valid complaint against you.
                </li>
                <li>
                  We may change this agreement in any way at any time. The
                  version applicable to your contract is the version which was
                  posted on Our Website at the time that the contract was made.
                </li>
              </ul>
            </li>
            <li>
              <h5>5.Listing your product/service in sastowholesale.com</h5>
              <p>
                Your product will be listed in product page directly but can be
                deleted if your product found issues, harm our society or not
                meet our requirement.
              </p>
            </li>
            <li>
              <h5>6.Restriction &amp; Responsibilities</h5>
              <ul>
                <li>
                  You agree not to use irrelevant tags, descriptions and
                  screenshots for product submitted by you for listing on
                  sastowholesale.com.
                </li>
                <li>
                  You agree not to deal or divert sastowholesale.com users
                  outside our website.
                </li>
                <li>
                  You represent and warrant that all intellectual property
                  rights in and to the products submitted for listing in
                  sastowholesale.com’s marketplace are duly licensed or owned by
                  you.
                </li>
                <li>
                  You are solely responsible for ensuring that your product does
                  not violate any third-party rights or any laws or regulations.
                </li>
                <li>
                  You agree to conduct yourself in a professional manner and not
                  to disparage the goodwill of sastowholesale.com or
                  sastowholesale.com’s marketplace.
                </li>
              </ul>
            </li>
            <li>
              <h5>7.Delivery &amp; Return</h5>
              <ul>
                <li>
                  For the customer service, we allow our vendors to send
                  directly to customer location or can use our logistics for
                  delivery.
                </li>
                <li>
                  If the buyer is requesting to return an item for “change of
                  mind” (or “remorse”) reasons, your return policy will apply
                  including which party is responsible for return postage costs.
                </li>
                <li>
                  In the event that a Product ordered is not available, you must
                  tell your customer and offer a replacement product or refund
                  any money paid.
                </li>
              </ul>
            </li>
            <li>
              <h5>8.The selling Procedure</h5>
              <ul>
                <li>
                  <h5>The Selling Procedure of Local Seller</h5>
                  <p>
                    While setting up the shop, it is important that you setup
                    your own terms &amp; conditions for buyers, such as return
                    &amp; refund policy. You can do this from your seller
                    portal. Please make sure to include or confirm the following
                    details in your listing or to your customer.
                  </p>
                  <ol>
                    <li>
                      Although, you will be allowed to do transaction outside
                      our website for Bank deposit, you need to create deals to
                      maintain website policy &amp; our commission.
                    </li>
                    <li>
                      Inform to check "My deals" to your customer in each new
                      deal.
                    </li>
                  </ol>
                </li>
                <li>
                  <h5>
                    The Selling Procedure of International seller to
                    International Buyer
                  </h5>
                  <p>
                    While setting up the shop, it is important that you setup
                    your own terms &amp; conditions for buyers, such as return
                    &amp; refund policy. You can do this from your seller
                    portal. Please make sure to include or confirm the following
                    details in your listing or to your customer.
                  </p>
                  <ol>
                    <li>Delivery &amp; Return policy</li>
                    <li>Taxes &amp; any applicable government imposed fees.</li>
                    <li>Terms of the transaction</li>
                    <li>
                      The buyer must have import license/Exim code for import.
                      So, Confirm if buyer have import license first.
                    </li>
                    <li>
                      Confirm if they have Purchase, Payment &amp; Transport
                      agent in your country.
                    </li>
                    <li>
                      Although, you will be allowed to do transaction outside
                      our website for TT/LC, you need to create deals to
                      maintain website policy &amp; our commission.
                    </li>
                    <li>
                      Inform to check "My deals" to your customer in each new
                      deal.
                    </li>
                    <li>
                      You must use Sastowholesale.com logistics only for
                      shipping to international buyers.
                    </li>
                  </ol>
                </li>
                <li>
                  You will receive a message by email at the time of each sale,
                  providing full information about that sale.
                </li>
              </ul>
            </li>
            <li>
              <h5>9.Goods, Service &amp; Government tax</h5>
              <p>
                • Buyers &amp; sellers are generally responsible for any sales
                tax, or other taxes that apply to items on our website.
              </p>
            </li>
            <li>
              <h5>10.Our commission &amp; Payment to you</h5>
              <ul>
                <li>
                  Joining sastowholesale.com marketplace as a seller &amp;
                  posting item is for free. We do retain a proportion of each
                  sale, with our mutual understanding based on your trading
                  role.
                </li>
                <li>
                  We will pay you within 24-48 hours after your payment request
                  to us.
                </li>
                <li>
                  You must do settlement your COD (Cash on delivery) to
                  Sastowholesale.com within 3 days after we informed you.
                </li>
                <li>
                  A buyer may from time to time use discount vouchers/ codes,
                  this total may be discounted from the total pay-out figure to
                  the seller.
                </li>
              </ul>
            </li>
            <li>
              <h5>11.Using our marketplace</h5>
              <p>
                We have to regulate your use of Our Website to protect our
                business and our staff, to protect other users of Our Website
                and to comply with the law. While using our website or platform,
                you will not:
              </p>
              <ul>
                <li>
                  Offer or reference your contact information or ask a buyer for
                  their contact information in the context of buying or selling
                  outside of sastowholesale.com Marketplace, you may be liable
                  to pay a commission fee applicable to that item.
                </li>
                <li>
                  Be obscene, offensive, threatening, violent or malicious.
                </li>
                <li>
                  Be unlawful, or tend to incite another person to commit a
                  crime.
                </li>
                <li>
                  Distribute or post spam, unsolicited or bulk electronic
                  communications, chain letters or pyramid schemes.
                </li>
              </ul>
            </li>
            <li>
              <h5>12.Security of our website</h5>
              <p>
                You now agree that you will not, and will not allow any other
                person to:
              </p>
              <ul>
                <li>
                  Share with a third party any login credentials to our website.
                </li>
                <li>
                  download any part of Our Website, without our express written
                  consent.
                </li>
                <li>
                  Link to Our Website in any way that would cause the appearance
                  or presentation of Our Website to be different from what would
                  be seen by a user who accessed Our Website by typing the URL
                  into a standard browser.
                </li>
                <li>
                  Modify, copy, or cause damage or unintended effect to any
                  portion of Our Website, or any software used within it.
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </frontmaster>
</template>

<script>
export default {};
</script>

<style scoped>
.heading h3,
h4,
.note {
  font-weight: 600;
  color: #7c7c7d;
}
.description {
  margin-left: 50px;
  margin-right: 50px;
}
.list {
  list-style: none;
  font-family: var(--font-primary);
  margin-bottom: 20px;
}
.list h5 {
  font-weight: 600;
  color: #495057;
  margin-bottom: 20px;
}
.list p {
  margin-left: 40px;
}
.list ul {
  list-style: disc;
}
.list ul,
ol {
  margin-left: 50px;
  margin-bottom: 20px;
}
.list ol {
  list-style-type: upper-roman;
}

@media (min-width: 320px) and (max-width: 768px) {
  .list h5 {
    width: 100%;
    text-align: center;
    flex-basis: unset;
  }
  .description {
    margin-left: 0;
    margin-right: 26px;
  }
}
</style>