<template>
  <frontmaster>
    <div class="container">
      <!-- section heading start -->
      <div class="heading mt-5">
        <h3>SASTOWHOLESALE.COM MARKETPLACE USER AGREEMENT</h3>
        <h4>
          Please read the “Terms of use” carefully before using
          sastowholesale.com
        </h4>
        <p class="note">
          ( This electronic record is generated by computer system &amp; does not
          require any physical or digital signatures. )
        </p>
      </div>
      <div class="row mt-5 mb-5">
        <div class="description">
          <ol class="list">
            <li>
              <strong>Acceptance through use</strong>
              <p>
                By purchasing or viewing any product, advertisement, or company
                profile, you agree to be bound by all of the Terms, conditions,
                and notices contained or referenced in these Terms. If you do
                not accept all of the Terms, you are not authorized to post or
                view any content of this website and shall discontinue using
                this website immediately.
              </p>
            </li>
            <li>
              <strong>Age Restriction</strong>
              <p>
                Sastowholesale.com is not directed to and is not authorized to
                post or view products by anyone under the age of Sixteen (16)
                and if you are using Sastowholesale.com on behalf of a legal
                entity, you shall be responsible to obtain the necessary
                authority to post or retrieve any information on the site and
                you agree to be accountable for that information.
              </p>
            </li>
            <li>
             <strong>Understanding the platform of Sastowholesale.com</strong>
              <p>
                You agree and understand that Sastowholesale.com is an internet
                platform that facilitates by providing communication between
                users (buyers, sellers, viewers etc.) for the purpose of sharing
                information of products or services. The information related to
                products, services, and companies are not related to
                Sastowholesale.com. You agree not to hold responsible for the
                information posted by these seller/vendor or for their act in
                any circumstances. Furthermore, you understand that
                Sastowholesale.com is not involved in any transaction of any
                products or services listed in this site, outside this platform.
                You will be given security if you deal within
                sastowholesale.com.
              </p>
            </li>
            <li>
             <strong>Limitation of Liability</strong><br><br>
              <ol>
                <li>
                  To the maximum extent permitted by law, The services provided
                  by Sastowholesale.com on or through the site are provided "AS
                  IS", "AS AVAILABLE" and “WITH ALL FAULTS”, and
                  Sastowholesale.com hereby expressly disclaims any and all
                  warranties of condition, quality, durability, performance,
                  accuracy, reliability, merchantability or fitness for a
                  particular purpose. All such warranties, representations,
                  conditions, and undertakings are hereby excluded.
                </li>
                <li>
                  To the maximum extent permitted by law, sastowholesale.com
                  makes no representations or warranties about the validity,
                  accuracy, correctness, reliability, quality, stability,
                  completeness or currentness of any information provided on or
                  through the sites; Sastowholesale.com does not represent or
                  warrant that the manufacture, importation, export,
                  distribution, offer, display, purchase, sale and/or use of
                  products or services offered or displayed on the sites does
                  not violate any third party rights; and Sastowholesale.com
                  makes no representations or warranties of any kind concerning
                  any product or service offered or displayed on the sites.
                </li>
                <li>
                  Any material downloaded or otherwise obtained through the
                  Sites or Services is done at each User's sole discretion and
                  risk and each User is solely responsible for any damage to its
                  own or to Sastowholesale.com’s computer system(s) or any loss
                  of data that may result from the download of any such
                  material. No advice or information, whether oral or written,
                  obtained by any user from Sastowholesale.com or through or
                  from the Sites shall create any warranty not expressly stated
                  herein.
                </li>
                <li>
                  The Sites may make available to User services or products
                  provided by independent third parties. No warranty or
                  representation is made with regard to such services or
                  products. In no event shall Sastowholesale.com or our
                  affiliates be held liable for any such services or products.
                </li>
                <li>
                  Each User hereby agrees to indemnify and hold
                  Sastowholesale.com, our affiliates, directors, officers and
                  employees harmless, from any and all losses, claims,
                  liabilities (including legal costs on a full indemnity basis)
                  which may arise from such User's access to or use of the Sites
                  or Services (including but not limited to the submission,
                  posting or display of such User's information and User Content
                  on the Sites, Sasto-wholesale Channels or Third Party Channels
                  under Promotion Services) or from your breach of any of the
                  representations, warranties hereunder and the terms and
                  conditions of the Terms. Each User hereby further agrees to
                  indemnify and hold Alibaba.com, our affiliates, directors,
                  officers and employees harmless, from any and all losses,
                  damages, claims, liabilities (including legal costs on a full
                  indemnity basis) which may arise from User's breach of any
                  representations and warranties made by User to
                  Sastowholesale.com, including but not limited to those set
                  forth in clause 5 hereunder.
                </li>
                <li>
                  Each User hereby further agrees to indemnify and save
                  Sastowholesale.com, our affiliates, directors, officers and
                  employees harmless, from any and all losses, damages, claims,
                  liabilities (including legal costs on a full indemnity basis)
                  which may arise, directly or indirectly, as a result of any
                  claims asserted by Third Party Rights claimants or other third
                  parties relating to the User Content, information and/or
                  products offered or displayed on the Sites. Each User hereby
                  further agrees that Sastowholesale.com is not responsible and
                  shall have no liability to you, for any material posted by
                  others, including defamatory, offensive or illicit material
                  and that the risk of damages from such material rests entirely
                  with each User. Sastowholesale.com reserves the right, at our
                  own expense, to assume the exclusive defense and control of
                  any matter otherwise subject to indemnification by you, in
                  which event you shall cooperate with Sastowholesale.com in
                  asserting any available defenses.
                </li>
                <li class="list2">
                  Sastowholesale.com shall not be liable for any special,
                  direct, indirect, punitive, incidental or consequential
                  damages or any damages whatsoever (including but not limited
                  to damages for loss of profits or savings, business
                  interruption, loss of information), whether in contract,
                  negligence, tort, equity or otherwise or any other damages
                  resulting from any of the following:
                  <ol>
                    <li>
                       The use or the inability to use the Sites or Services.
                    </li>
                    <li>
                      Any defect in goods, samples, data, information or
                      services purchased or obtained from a User or any other
                      third party through the Sites or Services
                    </li>
                    <li>
                      Violation of Third Party Rights or claims or demands that
                      User's manufacture, importation, exportation,
                      distribution, offer, display, purchase, sale and/or use of
                      products or services offered or displayed on the Sites or
                      through the Services may violate or may be asserted to
                      violate Third Party Rights or claims by any party that
                      they are entitled to defense or indemnification in
                      relation to assertions of rights, demands or claims by
                      Third Party Rights claimants
                    </li>
                    <li>
                      Unauthorized access by third parties to data or private
                      information of any User
                    </li>
                    <li>
                      Statements or conduct of any User of the Sites or
                      Services
                    </li>
                    <li>
                     Any matters relating to the Sites or Services, however
                      arising, including negligence.
                    </li>
                  </ol>
                </li>
                <li>
                  Notwithstanding any of the foregoing provisions, the aggregate
                  liability of Sastowholesale.com, our employees, agents,
                  affiliates, representatives or anyone acting on our behalf
                  with respect to each User for all claims arising from the
                  access to or use of the Sites or Services during any calendar
                  year shall be limited to the greater of (a) the amount of fees
                  the User has paid to Sastowholesale.com in exchange for the
                  access to or use of the Site or Services during the calendar
                  year and (b) the maximum amount permitted under the applicable
                  law. The preceding sentence shall not preclude the requirement
                  by the User to prove actual damages. All claims arising from
                  the use of the Sites or Services must be filed within one (1)
                  year from the date the cause of action arose or such longer
                  period as prescribed under the applicable law governing the
                  terms
                </li>
                <li>
                  The limitations and exclusions of liability to you under the
                  Terms shall apply to the maximum extent permitted by law and
                  shall apply whether or not Sastowholesale.com has been advised
                  of or should have been aware of the possibility of any such
                  losses arising.
                </li>
              </ol>
            </li>
            <li>
              <strong>Intellectual Property rights</strong>
              <p>
                Sastowholesale.com is the sole owner or lawful licensee of all
                the rights &amp; interests in the sites and the sites content. The
                Sites and Site Content embody trade secrets and other
                intellectual property rights protected under worldwide copyright
                and other laws. All title, ownership &amp; intellectual property
                rights in the Sites &amp; Site Content shall remain with
                Sastowholesale.com.
              </p>
            </li>
            <li>
              <strong>Transaction Between Buyers and Sellers</strong>
              <p>
                Through the sites, Sastowholesale.com provides electronic
                web-based platforms for exchanging information between buyers
                and sellers of product and services. Sastowholesale.com
                additionally provides electronic web-based transaction platform
                for members to place, accept, conclude, manage and fulfill
                orders for the provision of products and services online within
                the sites subject to the terms of the transaction services
                agreement. However, for any services, Sastowholesale.com does
                not represent either the seller or the buyer in specific
                transactions. Sastowholesale.com does not control and is not
                liable or responsible for the quality, safety, lawfulness or
                availability of the products or services offered for sale on the
                Sites, the ability of sellers to complete the sale or the
                ability of buyers to complete a purchase.
              </p>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </frontmaster>
</template>

<script>
export default {};
</script>

<style scoped>

.heading h3,
h4,
.note {
  font-weight: 600;
  color: #7c7c7d;
}
.description{
  padding-right: 16px;
   padding-left: 32px;
}
ol {
  list-style: none;
  counter-reset: cupcake;
  list-style-position: outside;
}
ol li p{
  margin-top: 20px;
}
ol li {
  counter-increment: cupcake;
  margin-bottom: 20px;
}
ol li:before {
  content: counters(cupcake, ".") ". ";
}

.list2 ol{
    list-style: lower-latin;
    counter-reset: none;
    margin-top: 10px;
}
.list2 ol li{
    counter-increment: none;
    margin-bottom: 10px;
    padding-right: 20px;
}
.list2 ol li::before{
    content: none;
}
@media (min-width: 768px) {
  .list2 ol li{
    margin-left: 50px;
}
}
@media (min-width: 320px) and (max-width: 768px) {
  .description ol li {
    width: 100%;
    flex-basis: unset;
  }
}
</style>