language: php

env:
  global:
    - APP_ENV=testing
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4
    - php: 7.4
      env: SETUP=lowest

services:
  - memcached
  - redis-server
  - mysql

before_script:
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f memcached redis
  - travis_retry composer self-update

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - vendor/bin/phpunit